const AccessoireProducts = [
    {
        productTitle: "Black Anchor Bracelet",
        ProductType: "Accessories",
        productPrice: "$150.00",
        productSrc: '/imgs/Anchor Bracelet.jpg',
        productId: '1',
        productLink: '/Basket/1',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        gender: "Woman",
        productColor: "Black",
    },
    {
        productTitle: "Black handBag",
        ProductType: "Accessories",
        productPrice: "$150.00",
        productSrc: '/imgs/BlackOverBag.jpg',
        productId: '4',
        productLink: '/Basket/4',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Black",

    },
    {
        productTitle: "Boho Bangle Bracelet",
        ProductType: "Accessories",
        productPrice: "$150.00",
        productSrc: '/imgs/Boho Bangle Bracelet.jpg',
        productId: '9',
        productLink: '/Basket/9',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Red",
        gender: "Woman",
    },
    {
        productTitle: "Bright Gold Purse",
        ProductType: "Accessories",
        productPrice: "$150.00",
        productSrc: '/imgs/Bright Gold Purse.jpg',
        productId: '10',
        productLink: '/Basket/10',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Gold",
        gender: "Woman",
    },
    {
        productTitle: "Bright Red Bag",
        ProductType: "Accessories",
        productPrice: "$150.00",
        productSrc: '/imgs/Bright Red Bag.jpg',
        productId: '11',
        productLink: '/Basket/11',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Red",
        gender: "Woman",
    },
    {
        productTitle: "Buddha Bracelet",
        ProductType: "Accessories",
        productPrice: "$150.00",
        productSrc: '/imgs/BraceletCudd.jpg',
        productId: '12',
        productLink: '/Basket/12',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Black",
        gender: "Men",
    },
    {
        productTitle: "Light Brown Purse",
        ProductType: "Accessories",
        productPrice: "$150.00",
        productSrc: "/imgs/Light Brown Purse.jpg",
        productId: '26',
        productLink: '/Basket/26',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Light Brown",
        gender: "Woman",
    },
    {
        productTitle: "Bright Yellow Bag",
        ProductType: "Accessories",
        productPrice: "$110.00",
        productSrc: "/imgs/Bright Yellow Bag.jpg",
        productId: '31',
        productLink: '/Basket/31',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Yellow",
        gender: "Woman",
    },
    {
        productTitle: "Red Boho Bangle Bracelet",
        ProductType: "Accessories",
        productPrice: "$170.00",
        productSrc: "/imgs/Red Boho Bangle Bracelet.jpg",
        productId: '32',
        productLink: '/Basket/32',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Red",
        gender: "Woman",
    },
    {
        productTitle: "Brown Anchor Bracelet",
        ProductType: "Accessories",
        productPrice: "$170.00",
        productSrc: "/imgs/Brown Anchor Bracelet.jpg",
        productId: '33',
        productLink: '/Basket/33',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Brown",
        gender: "Woman",
    }
];
export default AccessoireProducts;


