import Footer from "./LayoutComponent/Footer/Footer";
import Header from "./LayoutComponent/Header/Header";
import Copy from "./LayoutComponent/Copy/Copy";
// import 'bootstrap/dist/css/bootstrap.min.css';
// import 'bootstrap/dist/css/bootstrap.min.css';
// import 'bootstrap/dist/css/bootstrap.min.css';
// import '@fortawesome/fontawesome-free/css/all.min.css';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import './globals.css';
export const metadata = {
  title: 'DNK Store',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" />        
        <link rel="icon" type="image/jpg" href="/imgs/logo-modified.png" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />

      </head>
      <body>
        <Header />
        <main> {children} </main>
        <Footer />
        <Copy />
      </body>
    </html>
  )
}
