const MenProducts = [
    {
        productTitle: "Black Hoodie",
        ProductType: "Men",
        productPrice: "$150.00",
        productSrc: '/imgs/BlackHoodie.jpg',
        productId: '3',
        productLink: '/Basket/3',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Black",
    },
    {
        productTitle: "Blue T-Shirt",
        ProductType: "Men",
        productPrice: "$150.00",
        productSrc: '/imgs/BlueHoodie.jpg',
        productId: '7',
        productLink: '/Basket/7',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Blue",
    },
    {
        productTitle: "Blue T-Shirt",
        ProductType: "Men",
        productPrice: "$40.00",
        productSrc: '/imgs/Blue Tshirt.jpg',
        productId: '8',
        productLink: '/Basket/8',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Blue",
    },
    {
        productTitle: "Buddha Bracelet",
        ProductType: "Accessories",
        productPrice: "$150.00",
        productSrc: '/imgs/BraceletCudd.jpg',
        productId: '12',
        productLink: '/Basket/12',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Black",
        gender: "Men",
    },
    {
        productTitle: "Dark Blue Denim Jeans",
        ProductType: "Men",
        productPrice: "$150.00",
        productSrc: '/imgs/BlueDenimJeans.jpg',
        productId: '13',
        productLink: '/Basket/13',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Dark Blue",
    },
    {
        productTitle: "Dark Brown Jeans",
        ProductType: "Men",
        productPrice: "$150.00",
        productSrc: '/imgs/JeansMen.jpg',
        productId: '14',
        productLink: '/Basket/14',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Dark Brown",
    },
    {
        productTitle: "Dark Gray Jeans",
        ProductType: "Men",
        productPrice: "$150.00",
        productSrc: '/imgs/DarkGrayJeans.jpg',
        productId: '15',
        productLink: '/Basket/15',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Dark Gray",
    },
    {
        productTitle: "DNK Blue Shoes",
        ProductType: "Men",
        productPrice: "$200.00",
        productSrc: '/imgs/sports-shoes Blue One.jpg',
        productId: '17',
        productLink: '/Basket/17',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Blue",
    },
    {
        productTitle: "DNK Green Shoes",
        ProductType: "Men",
        productPrice: "$250.00",
        productSrc: '/imgs/DNK Green Shoes.jpg',
        productId: '18',
        productLink: '/Basket/18',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Green",
    },
    {
        productTitle: "DNK Green T-Shirt",
        ProductType: "Men",
        productPrice: "$44.00",
        productSrc: '/imgs/DNK Green T-Shirt.jpg',
        productId: '19',
        productLink: '/Basket/19',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Green",
    },
    {
        productTitle: "DNK Red Shoes",
        ProductType: "Men",
        productPrice: "$150.00",
        productSrc: '/imgs/DNK Red Shoes.jpg',
        productId: '20',
        productLink: '/Basket/20',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Red",
    },
    {
        productTitle: "DNK Yellow Shoes",
        ProductType: "Men",
        productPrice: "$120.00",
        productSrc: '/imgs/sports-shoe3.jpg',
        productId: '21',
        productLink: '/Basket/21',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Yellow",
    },
    {
        productTitle: "Faint Washed Denim Blue Jeans",
        ProductType: "Men",
        productPrice: "$150.00",
        productSrc: '/imgs/Faint Jeans.jpg',
        productId: '22',
        productLink: '/Basket/22',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Blue",
    },
    {
        productTitle: "Green Hoodie",
        ProductType: "Men",
        productPrice: "$150.00",
        productSrc: '/imgs/Green Hoodie.jpg',
        productId: '25',
        productLink: '/Basket/25',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Green",
    },
    {
        productTitle: "Red Hoodie",
        ProductType: "Men",
        productPrice: "$150.00",
        productSrc: "/imgs/Red Hoodie.jpg",
        productId: '29',
        productLink: '/Basket/29',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Red",
    },  
];
export default MenProducts;


