const WomanProducts = [
    {
        productTitle: "Black Anchor Bracelet",
        ProductType: "Accessories",
        productPrice: "$150.00",
        productSrc: '/imgs/Anchor Bracelet.jpg',
        productId: '1',
        productLink: '/Basket/1',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        gender: "Woman",
        productColor: "Black",
    },
    {
        productTitle: "Basic Gray Jeans",
        ProductType: "Woman",
        productPrice: "$150.00",
        productSrc: '/imgs/jeansWoman2.jpg',
        productId: '2',
        productLink: '/Basket/2',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Gray",

    },
    {
        productTitle: "Black handBag",
        ProductType: "Accessories",
        productPrice: "$150.00",
        productSrc: '/imgs/BlackOverBag.jpg',
        productId: '4',
        productLink: '/Basket/4',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Black",

    },
    {
        productTitle: "Blue Denim Jeans",
        ProductType: "Woman",
        productPrice: "$150.00",
        productSrc: '/imgs/jeansWoman1.jpg',
        productId: '5',
        productLink: '/Basket/5',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Blue",
    },
    {
        productTitle: "Blue Denim Short",
        ProductType: "Woman",
        productPrice: "$150.00",
        productSrc: '/imgs/BlueDenim Short.jpg',
        productId: '6', 
        productLink: '/Basket/6',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Blue",
    },
    {
        productTitle: "Boho Bangle Bracelet",
        ProductType: "Accessories",
        productPrice: "$150.00",
        productSrc: '/imgs/Boho Bangle Bracelet.jpg',
        productId: '9',
        productLink: '/Basket/9',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Red",
        gender: "Woman",
    },
    {
        productTitle: "Bright Gold Purse",
        ProductType: "Accessories",
        productPrice: "$150.00",
        productSrc: '/imgs/Bright Gold Purse.jpg',
        productId: '10',
        productLink: '/Basket/10',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Gold",
        gender: "Woman",
    },
    {
        productTitle: "Bright Red Bag",
        ProductType: "Accessories",
        productPrice: "$150.00",
        productSrc: '/imgs/Bright Red Bag.jpg',
        productId: '11',
        productLink: '/Basket/11',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Red",
        gender: "Woman",
    },
    {
        productTitle: "DNK Black Shoes",
        ProductType: "Woman",
        productPrice: "$175.00",
        productSrc: '/imgs/DNKBlackShoes.jpg',
        productId: '16',
        productLink: '/Basket/16',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Black",
    },
    {
        productTitle: "Flamingo T-Shirt",
        ProductType: "Woman",
        productPrice: "$28.00",
        productSrc: '/imgs/Flamingo Tshirt.jpg',
        productId: '23',
        productLink: '/Basket/23',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Red",
    },
    {
        productTitle2: "Orange Pattern T-Shirt",
        ProductType: "Woman",
        productPrice: "$33.00",
        productSrc: '/imgs/Gray Pattern T-Shirt.jpg',
        productId: '24',
        productLink: '/Basket/24',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Orange",
    },
    {
        productTitle: "Light Brown Purse",
        ProductType: "Accessories",
        productPrice: "$150.00",
        productSrc: "/imgs/Light Brown Purse.jpg",
        productId: '26',
        productLink: '/Basket/26',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Light Brown",
        gender: "Woman",
    },
    {
        productTitle: "Lemons T-Shirt",
        ProductType: "Woman",
        productPrice: "$28.00",
        productSrc: "/imgs/Lemons T-Shirt.jpg",
        productId: '27',
        productLink: '/Basket/27',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Lemons",
    },
    {
        productTitle: "Purple Tshirt",
        ProductType: "Woman",
        productPrice: "$27.00",
        productSrc: "/imgs/Purple T-Shirt.jpg",
        productId: '28',
        productLink: '/Basket/28',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Purple",
    },
    {
        productTitle: "Slim Fit Blue Jeans",
        ProductType: "Woman",
        productPrice: "$150.00",
        productSrc: "/imgs/Slim Fit Blue Jeans.jpg",
        productId: '30',
        productLink: '/Basket/30',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Blue",
    },
    {
        productTitle: "Bright Yellow Bag",
        ProductType: "Accessories",
        productPrice: "$110.00",
        productSrc: "/imgs/Bright Yellow Bag.jpg",
        productId: '31',
        productLink: '/Basket/31',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Yellow",
        gender: "Woman",
    },
    {
        productTitle: "Red Boho Bangle Bracelet",
        ProductType: "Accessories",
        productPrice: "$170.00",
        productSrc: "/imgs/Red Boho Bangle Bracelet.jpg",
        productId: '32',
        productLink: '/Basket/32',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Red",
        gender: "Woman",
    },
    {
        productTitle: "Brown Anchor Bracelet",
        ProductType: "Accessories",
        productPrice: "$170.00",
        productSrc: "/imgs/Brown Anchor Bracelet.jpg",
        productId: '33',
        productLink: '/Basket/33',
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        productColor: "Brown",
        gender: "Woman",
    }
];
export default WomanProducts;


